/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BORRAR.java
 *
 * Created on 19-jun-2012, 16:16:10
 */
package index;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.ChangeEvent;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CKaiser
 */
public class BORRAR extends javax.swing.JFrame {
    MiModelo dtmData = new MiModelo();
    /** Creates new form BORRAR */
    public BORRAR() {
        initComponents();
        /*http://docs.oracle.com/javase/tutorial/uiswing/components/table.html#sorting*/
        dtmData.addColumn("precio");
        dtmData.addColumn("cantidad");
        dtmData.addColumn("total");
        dtmData.addColumn("borrar");
        Object[] nuevaFila = {2, 2, 3, true};
        dtmData.addRow(nuevaFila);        
        dtmData.addRow(nuevaFila);
        
        data.getModel().addTableModelListener(new TableModelListener() {

            public void tableChanged(TableModelEvent e) {
                dtmData.removeTableModelListener(this);
                recalcular();                
                dtmData.addTableModelListener(this);
            }
            
          /*public void editingStopped(TableModelEvent e) {
             recalcular();
          }

            public void tableChanged(TableModelEvent e) {
                throw new UnsupportedOperationException("Not supported yet.");
            }*/
        });
        
        /*JTable data = new JTable(dtmData) {
      public void editingStopped(ChangeEvent e) {
        super.editingStopped(e);
        recalcular();
        repaint();
      }
    };*/
                
    }
    
    public class MiModelo extends DefaultTableModel
    {
       @Override
       public boolean isCellEditable (int row, int column)
       {
           // Aquí devolvemos true o false según queramos que una celda
           // identificada por fila,columna (row,column), sea o no editable
           //int s =0;
           if (column == 1)
           {
                Double precio = Double.parseDouble(""+dtmData.getValueAt(row, 0));
                Double cantidad = Double.parseDouble(""+dtmData.getValueAt(row, 1));
                Double total = precio * cantidad;
                //dtmData.setValueAt(total, row, 2);
                return true;
               //s = column+1;
              
           }           
           
                return false;
           
       }
       
        @Override
       public Class getColumnClass(int columna)
       {
          if (columna == 0) return Double.class;
          if (columna == 1) return Double.class;
          if (columna == 2) return Double.class;
          if (columna == 3) return Boolean.class;
          
          return Object.class;
          
       }
       
       //public void setValueAt(Object value, int row, int col) {
        //data[row][col] = value;
        //fireTableCellUpdated(row, col);
        //}
       
       //public void editingStopped(ChangeEvent e) {
        //if(data..editingStopped(e))
           //recalcular();  
        //recalcular();
        //repaint();
      //}
        /*@Override
        public void setValueAt(Object aValue, int rowIndex, int columnIndex) {
            recalcular();
        } */
       /*public void editingStopped(ChangeEvent e) {
        
        recalcular();
        repaint();
      }*/
        
            
      /* public void setValueAt(Object aValue, int rowIndex, int columnIndex) {
            switch(columnIndex){
                case 4:
                {    //int nuevaCantidad = Integer.valueOf(aValue.toString());
                    int nuevaCantidad = 700;
                    setValueAt(nuevaCantidad, rowIndex, 6);
                }
            }
            // Disparamos el Evento TableDataChanged (La tabla ha cambiado)
            fireTableDataChanged();

        } */
    } 
    public void recalcular()
    {
       // dtmData.setValueAt(89, 1, 1);
        //JOptionPane.showMessageDialog(this, "se esta editando", "Atención!", JOptionPane.INFORMATION_MESSAGE); 
        Double total = 0.00;
        int maxData = dtmData.getRowCount();
        for(int i=0; i<maxData; i++)
        {
            total = Double.parseDouble(""+dtmData.getValueAt(i, 0)) * Double.parseDouble(""+dtmData.getValueAt(i, 1));
            //System.out.println(total);
            dtmData.setValueAt(total, i, 2);
        }
        System.out.println("s");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        data = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        data.setModel(dtmData);
        data.setName("data"); // NOI18N
        jScrollPane1.setViewportView(data);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(stinventario.STInventarioApp.class).getContext().getResourceMap(BORRAR.class);
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(172, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(150, 150, 150))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    if(data.isEditing())
        JOptionPane.showMessageDialog(this, "se esta editando", "Atención!", JOptionPane.INFORMATION_MESSAGE);        
                
}//GEN-LAST:event_jButton1ActionPerformed
public void editingStopped(ChangeEvent e) {
        System.out.println("A cell has been edited.");
    }

    /**
     * Listens for cells where editing has been canceled (cell data has not been
     * changed).
     */
    public void editingCanceled(ChangeEvent e) {
        System.out.println("Editing of a cell has been canceled.");
    }

    //public void editingStopped(ChangeEvent e) {
        //JOptionPane.showMessageDialog(this, "termino de  editar", "Atención!", JOptionPane.INFORMATION_MESSAGE);   
        //recalcular();
        //repaint();
    //try {  
                   //JOptionPane.showMessageDialog(this, "termino de  editar", "Atención!", JOptionPane.INFORMATION_MESSAGE); 
                   //Integer intResult = Integer.parseInt(((dtmData) e.getSource()).getCellEditorValue().toString());  
                    //setValueAt(intResult, editingRow, editingColumn);  
                    //super.editingStopped(e);  
                //}  
               // catch (NumberFormatException ne) {  
                    //JOptionPane.showMessageDialog(null, "NumberFormatException Thrown");  
                    //return;  
                //}  
      //}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BORRAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BORRAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BORRAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BORRAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new BORRAR().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable data;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
