/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmReporteVentas.java
 *
 * Created on 10-jul-2012, 17:11:43
 */
package reportes;

import clases.clsCabecera;
import clases.clsCaja;
import clases.clsPago;
import clases.clsReporte;
import clases.clsUtils;
import index.main;
import java.awt.Dimension;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import pago.frmPagoDetalle;
import pago.frmPagoDetalleFactura;
import pago.frmPagoDetalleOtros;
import stinventario.frmPrincipal;
/**
 *
 * @author CKaiser
 */
public class frmListPagosPendientes extends javax.swing.JInternalFrame {
    clsUtils objUtils = new clsUtils();
    clsPago objPago = new clsPago();
    MiModelo dtmData = new MiModelo();
    clsReporte objReporte = new clsReporte();
    clsCaja objCaja = new clsCaja();
    Double totalEfectivo = 0.00;    
    /** Creates new form frmReporteVentas */
    public frmListPagosPendientes() {
        initComponents();
        
        dtmData.addColumn("N°");/*.setPreferredWidth(500)*/
        dtmData.addColumn("ID");
        dtmData.addColumn("FECHA DEL PAGO");
        dtmData.addColumn("CLIENTE");
        dtmData.addColumn("VALOR DEL PAGO");
        dtmData.addColumn("USUARIO");
        dtmData.addColumn("REFERENCIA");  
        dtmData.addColumn("REGISTRO");
        dtmData.addColumn("DOCUMENTO");  
                
        
        //ALINEAR COLUMNA
        DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
        tcr.setHorizontalAlignment(SwingConstants.RIGHT);
        tblData.getColumnModel().getColumn(3).setCellRenderer(tcr);        
        
        tblData.setAutoCreateRowSorter(true); 
        
        //OBTENER CAJERO
        String cajero = objCaja.obtenerCajero(main.idUser);
        lblCajero.setText(cajero);
        //NOMBRE USUARIO
        lblUsuario.setText(main.nameUser);
        
        buscar_informacion();
    }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        lblCajero = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(stinventario.STInventarioApp.class).getContext().getResourceMap(frmListPagosPendientes.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setName("jPanel2"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tblData.setModel(dtmData);
        tblData.setName("tblData"); // NOI18N
        tblData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblData);

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        txtTotal.setFont(resourceMap.getFont("txtTotal.font")); // NOI18N
        txtTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTotal.setText(resourceMap.getString("txtTotal.text")); // NOI18N
        txtTotal.setName("txtTotal"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(573, 573, 573)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap())
        );

        jLabel9.setFont(resourceMap.getFont("jLabel9.font")); // NOI18N
        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N

        lblCajero.setFont(resourceMap.getFont("lblCajero.font")); // NOI18N
        lblCajero.setText(resourceMap.getString("lblCajero.text")); // NOI18N
        lblCajero.setName("lblCajero"); // NOI18N

        jLabel22.setFont(resourceMap.getFont("jLabel22.font")); // NOI18N
        jLabel22.setText(resourceMap.getString("jLabel22.text")); // NOI18N
        jLabel22.setName("jLabel22"); // NOI18N

        lblUsuario.setFont(resourceMap.getFont("lblUsuario.font")); // NOI18N
        lblUsuario.setText(resourceMap.getString("lblUsuario.text")); // NOI18N
        lblUsuario.setName("lblUsuario"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCajero)
                        .addGap(52, 52, 52)
                        .addComponent(jLabel22)
                        .addGap(18, 18, 18)
                        .addComponent(lblUsuario)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblCajero)
                    .addComponent(jLabel22)
                    .addComponent(lblUsuario))
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void tblDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataMouseClicked
    int fila = tblData.rowAtPoint(evt.getPoint());
    int columna = tblData.columnAtPoint(evt.getPoint());
    /*int columna = 3;*/
    /*if ((fila > -1) && (columna > -1))*/
    int i = tblData.getSelectedRow();
    int idPago = Integer.parseInt(""+tblData.getValueAt(i, 1));
    //System.out.println("x:" + idCabecera + " " + fila + " " + columna);
    //objReporte.ejecutarReporteParametroInt(idCabecera, "rptPagosFactura"); 
    /*frmComprasShow ventana = new frmComprasShow(null, true, idCabecera);
    ventana.setLocationRelativeTo(null);
    ventana.setVisible(true);*/
    if(tblData.getValueAt(i, 8).equals("NE"))
    {   
        frmPagoDetalle formulario = new frmPagoDetalle(idPago);
        mostrarJInternalCentrado(formulario);  
    }
    else if(tblData.getValueAt(i, 8).equals("FACTURA"))
    {
        frmPagoDetalleFactura formulario = new frmPagoDetalleFactura(idPago);
        mostrarJInternalCentrado(formulario); 
    }
    else
    {
        frmPagoDetalleOtros formulario = new frmPagoDetalleOtros(idPago);
        mostrarJInternalCentrado(formulario); 
    }
    dispose();
}//GEN-LAST:event_tblDataMouseClicked
    public void llenarData(ArrayList<clsPago> dataPago, String documento)
    {        
        DecimalFormat df1 = new DecimalFormat("##0.00"); 
       
        int maxData = dataPago.size();  
        String fecha_realizada = "";
        String fecha_registro = "";

        for(int i=0; i<maxData; i++)
        {                    
             //fecha_realizada = dataPago.get(i).getFechaPago().substring(0, 16);    
             fecha_realizada = dataPago.get(i).getFechaPago().substring(0, 10);    
             fecha_registro = dataPago.get(i).getFechaRegistro().substring(0, 16);    
             Object[] nuevaFila = {  i+1, 
                                    dataPago.get(i).getIdPago(),
                                    fecha_realizada,
                                    dataPago.get(i).getNombreCliente(),
                                    "$ " + df1.format(dataPago.get(i).getValor()), 
                                    dataPago.get(i).getNombreUsuario(),   
                                    dataPago.get(i).getReferencia(),
                                    fecha_registro,
                                    documento
             };        

             totalEfectivo = totalEfectivo + dataPago.get(i).getValor();             
             dtmData.addRow(nuevaFila); 
        }         
        txtTotal.setText("" + (objUtils.redondear(totalEfectivo)));     
        
    }
     
    public void buscar_informacion()
    {
        objUtils.vaciarTabla(dtmData);        

        DateFormat df1 = new SimpleDateFormat("yyyy-MM-dd");            
      
        try
        {
            ArrayList<clsPago> dataPago = objPago.consultaDataPagosPendientes();
            int maxData = dataPago.size();
            if (maxData==0)
            {}
            else
            {
                llenarData(dataPago, "NE");    
            }
        }
        catch(Exception e)
        {}
        /*if(dataPago.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "No existen datos", "Atención!", JOptionPane.WARNING_MESSAGE);
        }
        else
        {                
            llenarData(dataPago, "NE");    
        } */    
        
        try{
            ArrayList<clsPago> dataPagoFactura = objPago.consultaDataPagosPendientesFactura();
        
            int maxData2 = dataPagoFactura.size();
            if (maxData2==0)
            {}
            else
            {
                llenarData(dataPagoFactura, "FACTURA");    
            }
        }
        catch(Exception e)
        {}
        
        try{
            ArrayList<clsPago> dataPagoOtros = objPago.consultaDataPagosPendientesOtros();
        
            int maxData3 = dataPagoOtros.size();
            if (maxData3==0)
            {}
            else
            {
                llenarData(dataPagoOtros, "OTROS");    
            }
        }
        catch(Exception e)
        {}
        
    }  
    
    public class MiModelo extends DefaultTableModel
    {
            @Override
       public boolean isCellEditable (int row, int column)
       {
           // Aquí devolvemos true o false según queramos que una celda
           // identificada por fila,columna (row,column), sea o no editable
          /* if (column == 3)
              return true;*/
           
           return false;
       }
    } 
    
    public static void mostrarJInternalCentrado(javax.swing.JInternalFrame formulario)
    {
        Dimension desktopSize = frmPrincipal.jDesktopPane1.getSize();
        Dimension jInternalFrameSize = formulario.getSize();
        formulario.setLocation((desktopSize.width - jInternalFrameSize.width)/2,
        (desktopSize.height- jInternalFrameSize.height)/2);

        frmPrincipal.jDesktopPane1.add(formulario);
        formulario.show(); 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCajero;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTable tblData;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
