/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package nomina;

import clases.clsEgreso;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ckaiser
 */
public class frmAdelantos extends javax.swing.JInternalFrame {
    MiModelo dtmData = new MiModelo();
    clsEgreso objEgreso = new clsEgreso();
    /**
     * Creates new form frmAdelantos
     */
    public frmAdelantos() {
        initComponents();
        
        dtmData.addColumn("id");
        dtmData.addColumn("N°");
        dtmData.addColumn("EMPLEADO");
        dtmData.addColumn("MOTIVO");
        dtmData.addColumn("CANTIDAD");
        dtmData.addColumn("FECHA");
        
        ArrayList<clsEgreso> dataAdelantos = objEgreso.consultaAdelantos();
        llenarData(dataAdelantos);
    }
    
    public void llenarData(ArrayList<clsEgreso> dataCompras)
    {
        Double total = 0.00;
        
        DecimalFormat df1 = new DecimalFormat("##0.00"); 
        int maxData = dataCompras.size();        
        String fecha = "";
        for(int i=0; i<maxData; i++)
        {
            
            fecha = dataCompras.get(i).getFecha().substring(0 , 16);             
            Object[] nuevaFila = {dataCompras.get(i).getIdEgreso(),
                                    i+1, 
                                    dataCompras.get(i).getNombre(),
                                    dataCompras.get(i).getConcepto(),                          
                                    dataCompras.get(i).getCantidadEgreso(),
                                    fecha
             };       
             //total = total + dataCompras.get(i).getTotal();
             dtmData.addRow(nuevaFila); 
        } 
        
    }
    
    public class MiModelo extends DefaultTableModel
    {
            @Override
       public boolean isCellEditable (int row, int column)
       {
           // Aquí devolvemos true o false según queramos que una celda
           // identificada por fila,columna (row,column), sea o no editable
          /* if (column == 3)
              return true;*/
           
           return false;
       }
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(stinventario.STInventarioApp.class).getContext().getResourceMap(frmAdelantos.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1.setModel(dtmData);
        jTable1.setName("jTable1"); // NOI18N
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
