/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmKardex.java
 *
 * Created on 29-nov-2011, 17:44:08
 */
package producto;

import clases.clsColorKardex;
import clases.clsComboBox;
import clases.clsKardex;
import clases.clsParametros;
import clases.clsPermisos;
import clases.clsPrecio;
import clases.clsProducto;
import clases.clsUtils;
import com.jidesoft.hints.ListDataIntelliHints;
import com.jidesoft.swing.SelectAllUtils;
import index.main;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.JXImagePanel.Style;
import pos.frmListProductos;
import stinventario.frmPrincipal;

/**
 *
 * @author CKaiser
 */
public class frmKardex extends javax.swing.JInternalFrame {
    MiModelo dtmData = new MiModelo();
    MiModelo dtmDataBodega = new MiModelo();
    clsKardex objKardex = new clsKardex();
    clsUtils objUtils = new clsUtils();
    clsProducto objProducto = new clsProducto();
    clsPermisos objPermisos = new clsPermisos();
    clsPrecio objPrecio = new clsPrecio(); 
    clsParametros objParametros = new clsParametros();
    
    String x_ruta = objParametros.consultaRutaImagenes();  
    //CODIGO DEL PRODUCTO SELECCIONADO 
    public static int codigoProducto;
    boolean permitido;
    
    /** Creates new form frmKardex */
    public frmKardex() {
        initComponents();
        
        dtmData.addColumn("Nº");                dtmDataBodega.addColumn("Nº");
        dtmData.addColumn("Fecha");             dtmDataBodega.addColumn("Fecha");
        dtmData.addColumn("Concepto");          dtmDataBodega.addColumn("Concepto");
        dtmData.addColumn("Proveedor/Cliente"); dtmDataBodega.addColumn("Proveedor/Cliente");
        dtmData.addColumn("Valor");             dtmDataBodega.addColumn("Valor");    
        dtmData.addColumn("Unidades");          dtmDataBodega.addColumn("Unidades");
        dtmData.addColumn("Costo");             dtmDataBodega.addColumn("Costo");
        dtmData.addColumn("Saldo");             dtmDataBodega.addColumn("Saldo");
        dtmData.addColumn("tipo_mov");          dtmDataBodega.addColumn("tipo_mov");
        dtmData.addColumn("Usuario");           dtmDataBodega.addColumn("Usuario");
        dtmData.addColumn("id_documento");      dtmDataBodega.addColumn("id_documento");
        //OCULTAR
        objUtils.setOcultarColumnasJTable(this.tblData, new int[]{8});  
        objUtils.setOcultarColumnasJTable(this.tblDataBodega, new int[]{8});  
         
        //ALINEAR COLUMNA
        DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
        tcr.setHorizontalAlignment(SwingConstants.RIGHT);
        tblData.getColumnModel().getColumn(4).setCellRenderer(tcr); tblDataBodega.getColumnModel().getColumn(4).setCellRenderer(tcr); 
        tblData.getColumnModel().getColumn(5).setCellRenderer(tcr); tblDataBodega.getColumnModel().getColumn(5).setCellRenderer(tcr); 
        tblData.getColumnModel().getColumn(6).setCellRenderer(tcr); tblDataBodega.getColumnModel().getColumn(6).setCellRenderer(tcr); 
        tblData.getColumnModel().getColumn(7).setCellRenderer(tcr); tblDataBodega.getColumnModel().getColumn(7).setCellRenderer(tcr); 
        
        //CARGAR AUTOCOMPLETAR
        List<String> dataCodigo = objProducto.consultarCodigos();         
        SelectAllUtils.install(txtCodigoProducto);
        ListDataIntelliHints intellihints = new ListDataIntelliHints(txtCodigoProducto, dataCodigo);        
        intellihints.setCaseSensitive(false);
        
        tblData.setDefaultRenderer (Object.class, new clsColorKardex());
        tblDataBodega.setDefaultRenderer (Object.class, new clsColorKardex());
    }
    
    public class MiModelo extends DefaultTableModel
    {
            @Override
       public boolean isCellEditable (int row, int column)
       {
           // Aquí devolvemos true o false según queramos que una celda
           // identificada por fila,columna (row,column), sea o no editable
          /* if (column == 3)
              return true;*/
           
           return false;
       }
    }   

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCodigoProducto = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnBuscarNombre = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        lblTexto = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbPrecio = new javax.swing.JComboBox();
        btnNuevo = new javax.swing.JButton();
        btnImagen = new javax.swing.JButton();
        imagepanel1 = new org.jdesktop.swingx.JXImagePanel();
        jLabel5 = new javax.swing.JLabel();
        txtBodega = new javax.swing.JTextField();
        btnRecibir = new javax.swing.JButton();
        btnRetirar = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDataBodega = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(stinventario.STInventarioApp.class).getContext().getResourceMap(frmKardex.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel1.border.title"))); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        txtCodigoProducto.setText(resourceMap.getString("txtCodigoProducto.text")); // NOI18N
        txtCodigoProducto.setName("txtCodigoProducto"); // NOI18N
        txtCodigoProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoProductoKeyTyped(evt);
            }
        });

        btnBuscar.setIcon(resourceMap.getIcon("btnBuscar.icon")); // NOI18N
        btnBuscar.setText(resourceMap.getString("btnBuscar.text")); // NOI18N
        btnBuscar.setName("btnBuscar"); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnBuscarNombre.setText(resourceMap.getString("btnBuscarNombre.text")); // NOI18N
        btnBuscarNombre.setFocusable(false);
        btnBuscarNombre.setName("btnBuscarNombre"); // NOI18N
        btnBuscarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarNombreActionPerformed(evt);
            }
        });

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        txtDescripcion.setEditable(false);
        txtDescripcion.setText(resourceMap.getString("txtDescripcion.text")); // NOI18N
        txtDescripcion.setName("txtDescripcion"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        txtStock.setEditable(false);
        txtStock.setText(resourceMap.getString("txtStock.text")); // NOI18N
        txtStock.setName("txtStock"); // NOI18N

        lblTexto.setText(resourceMap.getString("lblTexto.text")); // NOI18N
        lblTexto.setName("lblTexto"); // NOI18N
        lblTexto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lblTextoFocusGained(evt);
            }
        });

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        cmbPrecio.setName("cmbPrecio"); // NOI18N

        btnNuevo.setIcon(resourceMap.getIcon("btnNuevo.icon")); // NOI18N
        btnNuevo.setText(resourceMap.getString("btnNuevo.text")); // NOI18N
        btnNuevo.setName("btnNuevo"); // NOI18N
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnImagen.setIcon(resourceMap.getIcon("btnImagen.icon")); // NOI18N
        btnImagen.setName("btnImagen"); // NOI18N
        btnImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImagenActionPerformed(evt);
            }
        });

        imagepanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        imagepanel1.setName("imagepanel1"); // NOI18N

        javax.swing.GroupLayout imagepanel1Layout = new javax.swing.GroupLayout(imagepanel1);
        imagepanel1.setLayout(imagepanel1Layout);
        imagepanel1Layout.setHorizontalGroup(
            imagepanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 109, Short.MAX_VALUE)
        );
        imagepanel1Layout.setVerticalGroup(
            imagepanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        txtBodega.setEditable(false);
        txtBodega.setText(resourceMap.getString("txtBodega.text")); // NOI18N
        txtBodega.setName("txtBodega"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBodega, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(29, 29, 29)
                        .addComponent(cmbPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(423, 423, 423)
                        .addComponent(lblTexto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBuscarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtCodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(18, 18, 18)
                .addComponent(btnImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(imagepanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(imagepanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnImagen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNuevo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(btnBuscarNombre)
                                .addComponent(txtCodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(cmbPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(txtBodega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTexto)))
                .addContainerGap())
        );

        btnRecibir.setIcon(resourceMap.getIcon("btnRecibir.icon")); // NOI18N
        btnRecibir.setText(resourceMap.getString("btnRecibir.text")); // NOI18N
        btnRecibir.setEnabled(false);
        btnRecibir.setName("btnRecibir"); // NOI18N
        btnRecibir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecibirActionPerformed(evt);
            }
        });

        btnRetirar.setIcon(resourceMap.getIcon("btnRetirar.icon")); // NOI18N
        btnRetirar.setText(resourceMap.getString("btnRetirar.text")); // NOI18N
        btnRetirar.setEnabled(false);
        btnRetirar.setName("btnRetirar"); // NOI18N
        btnRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarActionPerformed(evt);
            }
        });

        jTabbedPane1.setName("jTabbedPane1"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tblData.setModel(dtmData);
        tblData.setName("tblData"); // NOI18N
        tblData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblData);

        jTabbedPane1.addTab(resourceMap.getString("jScrollPane1.TabConstraints.tabTitle"), jScrollPane1); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        tblDataBodega.setModel(dtmDataBodega);
        tblDataBodega.setName("tblDataBodega"); // NOI18N
        tblDataBodega.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataBodegaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblDataBodega);

        jTabbedPane1.addTab(resourceMap.getString("jScrollPane2.TabConstraints.tabTitle"), jScrollPane2); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnRecibir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRetirar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRecibir, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnBuscarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarNombreActionPerformed
     frmListProductos ventana = new frmListProductos(null, true, "3", 0);        
     ventana.setLocationRelativeTo(null);
     ventana.setVisible(true);
}//GEN-LAST:event_btnBuscarNombreActionPerformed

private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
    cargarData();
}//GEN-LAST:event_btnBuscarActionPerformed
    
    public void cargarData()
    {
        txtCodigoProducto.setEnabled(false);
        btnBuscarNombre.setEnabled(false);
        String codProducto = txtCodigoProducto.getText().toString();
     
        ArrayList<clsProducto> dataProducto = objProducto.consultarDataProductoPorCodigo(codProducto); 
        Double saldo = 0.00;
        
        if(dataProducto.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Revisar datos ", "Atención", JOptionPane.ERROR_MESSAGE);
            objUtils.vaciarTabla(dtmData);
            objUtils.vaciarTabla(dtmDataBodega);
            txtCodigoProducto.requestFocus();
        }
        else
        {    
            codigoProducto = Integer.parseInt(dataProducto.get(0).getIdItems());
            txtDescripcion.setText(dataProducto.get(0).getDesItem());
            txtStock.setText(""+dataProducto.get(0).getCantStock());
            txtBodega.setText(""+dataProducto.get(0).getCantBodega());
            ArrayList <clsKardex> dataKardex = objKardex.consultarMovimientos("" + codigoProducto);
            objUtils.vaciarTabla(dtmData);
            objUtils.vaciarTabla(dtmDataBodega);
            
            String nombreRandomico = "";
             try{
                if(dataProducto.get(0).getImagen().isEmpty()||
                        dataProducto.get(0).getImagen()==null||
                        dataProducto.get(0).getImagen().equals(""))
                {}
                else
                {
                    nombreRandomico = dataProducto.get(0).getImagen();
                    String ruta = x_ruta + nombreRandomico;
                    //rutaActual = x_ruta + nombreRandomico + ".jpg";
                    mostrarImagen(ruta);

                }      
            }
            catch(Exception e){
              //JOptionPane.showMessageDialog(null, e);
            }
             
            for(int i=0; i<dataKardex.size(); i++)
            {
                int localidad = dataKardex.get(i).getIdLocalidad();
                if (i==0)
                    saldo = dataKardex.get(i).getUnidades();
                else
                    saldo = saldo + (dataKardex.get(i).getUnidades());
                Object[] nuevaFila = {i+1 
                                        , dataKardex.get(i).getFecha().substring(1, 16)
                                        , dataKardex.get(i).getDescripcion()
                                        , dataKardex.get(i).getIdEmpresa() + " - " + dataKardex.get(i).getNombreEmpresa()
                                        , "$ " + dataKardex.get(i).getValor()
                                        , dataKardex.get(i).getUnidades()
                                        , dataKardex.get(i).getCosto()
                                        , saldo
                                        , dataKardex.get(i).getTipoMov()
                                        , dataKardex.get(i).getName()
                                        , dataKardex.get(i).getIdDocumento()};
                if(localidad ==1)
                    dtmData.addRow(nuevaFila); 
                else if(localidad==2)
                    dtmDataBodega.addRow(nuevaFila); 
                    
            }
            //CARGAR PRECIOS DEL PRODUCTO
            cmbPrecio.removeAllItems();                
            ArrayList<clsComboBox> dataPrecios = objPrecio.consultarPrecios("" + codigoProducto);        
            if(dataPrecios.isEmpty())
            {}
            else
            {
                for(int i=0;i<dataPrecios.size();i=i+1)
                {
                    clsComboBox oItem = new clsComboBox(dataPrecios.get(i).getDescripcion(), 
                            dataPrecios.get(i).getCodigo() + " - " + dataPrecios.get(i).getDescripcion());
                    cmbPrecio.addItem(oItem);            
                }
            }
            this.btnRecibir.setEnabled(true);
            this.btnRetirar.setEnabled(true);
            
            
        }
    }
    
    public void mostrarImagen(String ruta)
    {
        BufferedImage img = null;
        try {
            img = ImageIO.read(new File(ruta));
        } catch (IOException e) {
            System.out.println(e.getMessage());
        }
        
        //JLabel etiqueta = new JLabel(imagen);
        //jPanel5.add(etiqueta);
       
        
        
        
        /*int ancho =imagepanel.getWidth();
        int alto = imagepanel.getHeight();
        Image x = redimensionarImagen(img, ancho, alto);
        imagepanel.setImage(x);
        imagepanel.setStyle(Style.CENTERED);  
        //imagepanel.setStyle(Style.SCALED);  
        imagepanel.setStyle(Style.SCALED_KEEP_ASPECT_RATIO);  
        imagepanel.setStyle(Style.TILED);  */
        
        
        //etiqueta.setBounds(0,0,300,200);
    }
    
    /*Retornar una imagen tipo Image, redimensionada, apartir de los parametros -
    alto y ancho proporcionados. */
    public Image redimensionarImagen(Image imagen, int ancho, int alto) {
        return imagen.getScaledInstance(ancho, alto, Image.SCALE_AREA_AVERAGING);
    }//FIN: redimensionarImagen.
    
private void btnRecibirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecibirActionPerformed
    permitido = objPermisos.comprobarPermisoFormulario(main.idUser, "frmKardexIngreso");
    if(permitido)
    {          
        frmKardexIngreso formulario = new frmKardexIngreso();      
        frmKardexIngreso.txtCodigo.setText(txtCodigoProducto.getText());
        frmKardexIngreso.txtDescripcion.setText(txtDescripcion.getText());
        frmKardexIngreso.codigoProducto = codigoProducto;
        frmPrincipal.mostrarJInternalCentrado(formulario);        
    }
    else
    {
        JOptionPane.showMessageDialog(this, objUtils.msgSinPermisosFormulario, objUtils.msgTitleSinPermisos, JOptionPane.WARNING_MESSAGE);            
    }
}//GEN-LAST:event_btnRecibirActionPerformed

private void btnRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarActionPerformed
    permitido = objPermisos.comprobarPermisoFormulario(main.idUser, "frmKardexEgreso");
    if(permitido)
    {          
        frmKardexEgreso formulario = new frmKardexEgreso();      
        frmKardexEgreso.txtCodigo.setText(txtCodigoProducto.getText());
        frmKardexEgreso.txtDescripcion.setText(txtDescripcion.getText());
        frmKardexEgreso.codigoProducto = codigoProducto;
        frmPrincipal.mostrarJInternalCentrado(formulario);        
    }
    else
    {
        JOptionPane.showMessageDialog(this, objUtils.msgSinPermisosFormulario, objUtils.msgTitleSinPermisos, JOptionPane.WARNING_MESSAGE);            
    }// TODO add your handling code here:
}//GEN-LAST:event_btnRetirarActionPerformed

private void txtCodigoProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoProductoKeyTyped
    if(evt.getKeyChar() == KeyEvent.VK_ENTER){  
        cargarData();   
    } 
}//GEN-LAST:event_txtCodigoProductoKeyTyped

private void lblTextoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblTextoFocusGained
    cargarData();
}//GEN-LAST:event_lblTextoFocusGained

private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
    txtCodigoProducto.setText("");
    txtCodigoProducto.setEnabled(true);
    txtCodigoProducto.requestFocus();
    txtDescripcion.setText("");
    txtStock.setText("");
    cmbPrecio.removeAllItems();
    objUtils.limpiarJTable(dtmData);
    objUtils.limpiarJTable(dtmDataBodega);
    btnBuscarNombre.setEnabled(true);
    
}//GEN-LAST:event_btnNuevoActionPerformed

private void btnImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImagenActionPerformed
    String imagen = objProducto.consultarImagenProducto(codigoProducto); 
    try
    {
        if(imagen.equals(""))
        {   
            JOptionPane.showMessageDialog(this, "No tiene imagen guardada", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            String rutaActual = x_ruta + imagen;    
            File f = new File(rutaActual);

            if(f.exists()){
                try {            
                    Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + rutaActual);
                }
                catch(Exception e){
                    System.out.println("" + e.getMessage());
                }        
            }
            else
                JOptionPane.showMessageDialog(this, "No existe\n" + rutaActual, "ERROR", JOptionPane.ERROR_MESSAGE);      
        }   
    }
    catch(Exception e){
        JOptionPane.showMessageDialog(this, "No tiene imagen guardada", "ERROR", JOptionPane.ERROR_MESSAGE);
    }  

}//GEN-LAST:event_btnImagenActionPerformed

    private void tblDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataMouseClicked
        //int fila = tblData.rowAtPoint(evt.getPoint());
        //int columna = tblData.columnAtPoint(evt.getPoint());

        int i = tblData.getSelectedRow();
        String descripcion = ""+tblData.getValueAt(i, 2);
        int idCabecera = Integer.parseInt("" + tblData.getValueAt(i, 10));
        System.out.println(descripcion.substring(0, 6) + "-" + idCabecera);
        if(descripcion.substring(0, 6).equals("COMPRA"))
        {
            frmComprasShow formulario = new frmComprasShow(idCabecera);
            mostrarJInternalCentrado(formulario);
        }
    }//GEN-LAST:event_tblDataMouseClicked

    private void tblDataBodegaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataBodegaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblDataBodegaMouseClicked

     public static void mostrarJInternalCentrado(javax.swing.JInternalFrame formulario)
    {
        Dimension desktopSize = frmPrincipal.jDesktopPane1.getSize();
        Dimension jInternalFrameSize = formulario.getSize();
        formulario.setLocation((desktopSize.width - jInternalFrameSize.width)/2,
        (desktopSize.height- jInternalFrameSize.height)/2);

        frmPrincipal.jDesktopPane1.add(formulario);
        formulario.show(); 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarNombre;
    private javax.swing.JButton btnImagen;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnRecibir;
    private javax.swing.JButton btnRetirar;
    public static javax.swing.JComboBox cmbPrecio;
    private org.jdesktop.swingx.JXImagePanel imagepanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    public static javax.swing.JLabel lblTexto;
    private javax.swing.JTable tblData;
    private javax.swing.JTable tblDataBodega;
    private javax.swing.JTextField txtBodega;
    public static javax.swing.JTextField txtCodigoProducto;
    public static javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
