/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmPagoAdd.java
 *
 * Created on 08-nov-2011, 10:25:57
 */
package pago;

import clases.clsAuditoria;
import clases.clsCliente;
import clases.clsCtasCobrar;
import clases.clsPago;
import clases.clsReporte;
import clases.clsUtils;
import com.jidesoft.hints.ListDataIntelliHints;
import com.jidesoft.swing.SelectAllUtils;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import pos.frmFactDeudaShow;
import pos.frmFactHistoShow;
import pos.frmListClientes;

/**
 *
 * @author CKaiser
 */
public class frmEstadoDeCuenta extends javax.swing.JInternalFrame {
    clsCliente objCliente = new clsCliente();
    clsCtasCobrar objCtasCobrar = new clsCtasCobrar();
    clsPago objPago = new clsPago();
    clsAuditoria objAuditoria = new clsAuditoria();
    clsUtils objUtils = new clsUtils();
    clsReporte objReporte = new clsReporte();
    
    public static String codigoCliente;
    Double saldoActual;
    /** Creates new form frmPagoAdd */
    MiModelo dtmData = new MiModelo();
    
    public frmEstadoDeCuenta() {
        initComponents();
        
        dtmData.addColumn("Nº");        
        dtmData.addColumn("Factura Referencia Monica");
        dtmData.addColumn("Descripcion");
        dtmData.addColumn("Valor");
        dtmData.addColumn("Saldo");
        dtmData.addColumn("idCtaCobrar");
        dtmData.addColumn("idCabecera");
        dtmData.addColumn("TIPO DE DOCUMENTO");        
        
        List<String> dataCedula = objCliente.consultarCedulas(); 
        SelectAllUtils.install(txtCedula);
        ListDataIntelliHints intellihints = new ListDataIntelliHints(txtCedula, dataCedula);
        intellihints.setCaseSensitive(false);
        
        //DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        //Date fechaActual = new Date();       
        
        tblData.setDefaultRenderer (Object.class, new colorFilaTable());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtCedula = new javax.swing.JTextField();
        txtNombreCliente = new javax.swing.JTextField();
        btnBuscarCliente = new javax.swing.JButton();
        chkDeudasCero = new javax.swing.JCheckBox();
        chkContado = new javax.swing.JCheckBox();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txtIdCuentaCobrar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        btnVerPagos = new javax.swing.JButton();
        btnVerFactura = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtTipoDocumento = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTotalDeuda = new javax.swing.JTextField();
        lblUsuarioTipo = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(stinventario.STInventarioApp.class).getContext().getResourceMap(frmEstadoDeCuenta.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel1.border.title"))); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtCedula.setText(resourceMap.getString("txtCedula.text")); // NOI18N
        txtCedula.setName("txtCedula"); // NOI18N
        txtCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaKeyTyped(evt);
            }
        });

        txtNombreCliente.setEditable(false);
        txtNombreCliente.setText(resourceMap.getString("txtNombreCliente.text")); // NOI18N
        txtNombreCliente.setName("txtNombreCliente"); // NOI18N

        btnBuscarCliente.setText(resourceMap.getString("btnBuscarCliente.text")); // NOI18N
        btnBuscarCliente.setName("btnBuscarCliente"); // NOI18N
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        chkDeudasCero.setText(resourceMap.getString("chkDeudasCero.text")); // NOI18N
        chkDeudasCero.setName("chkDeudasCero"); // NOI18N
        chkDeudasCero.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkDeudasCeroItemStateChanged(evt);
            }
        });

        chkContado.setText(resourceMap.getString("chkContado.text")); // NOI18N
        chkContado.setName("chkContado"); // NOI18N
        chkContado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkContadoItemStateChanged(evt);
            }
        });

        txtDireccion.setEditable(false);
        txtDireccion.setText(resourceMap.getString("txtDireccion.text")); // NOI18N
        txtDireccion.setName("txtDireccion"); // NOI18N

        txtTelefono.setEditable(false);
        txtTelefono.setText(resourceMap.getString("txtTelefono.text")); // NOI18N
        txtTelefono.setName("txtTelefono"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(14, 14, 14))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtCedula)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarCliente))
                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkDeudasCero)
                    .addComponent(chkContado)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(btnBuscarCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(chkDeudasCero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkContado)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel2.border.title"))); // NOI18N
        jPanel2.setName("jPanel2"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tblData.setModel(dtmData);
        tblData.setName("tblData"); // NOI18N
        tblData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblData);

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        txtIdCuentaCobrar.setEditable(false);
        txtIdCuentaCobrar.setText(resourceMap.getString("txtIdCuentaCobrar.text")); // NOI18N
        txtIdCuentaCobrar.setName("txtIdCuentaCobrar"); // NOI18N

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        txtDescripcion.setColumns(20);
        txtDescripcion.setEditable(false);
        txtDescripcion.setRows(5);
        txtDescripcion.setName("txtDescripcion"); // NOI18N
        jScrollPane2.setViewportView(txtDescripcion);

        btnVerPagos.setIcon(resourceMap.getIcon("btnVerPagos.icon")); // NOI18N
        btnVerPagos.setText(resourceMap.getString("btnVerPagos.text")); // NOI18N
        btnVerPagos.setToolTipText(resourceMap.getString("btnVerPagos.toolTipText")); // NOI18N
        btnVerPagos.setActionCommand(resourceMap.getString("btnVerPagos.actionCommand")); // NOI18N
        btnVerPagos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnVerPagos.setName("btnVerPagos"); // NOI18N
        btnVerPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerPagosActionPerformed(evt);
            }
        });

        btnVerFactura.setIcon(resourceMap.getIcon("btnVerFactura.icon")); // NOI18N
        btnVerFactura.setText(resourceMap.getString("btnVerFactura.text")); // NOI18N
        btnVerFactura.setToolTipText(resourceMap.getString("btnVerFactura.toolTipText")); // NOI18N
        btnVerFactura.setActionCommand(resourceMap.getString("btnVerFactura.actionCommand")); // NOI18N
        btnVerFactura.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnVerFactura.setName("btnVerFactura"); // NOI18N
        btnVerFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerFacturaActionPerformed(evt);
            }
        });

        jLabel10.setText(resourceMap.getString("jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N

        txtTipoDocumento.setEditable(false);
        txtTipoDocumento.setText(resourceMap.getString("txtTipoDocumento.text")); // NOI18N
        txtTipoDocumento.setName("txtTipoDocumento"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        txtTotalDeuda.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTotalDeuda.setText(resourceMap.getString("txtTotalDeuda.text")); // NOI18N
        txtTotalDeuda.setName("txtTotalDeuda"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel6))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtIdCuentaCobrar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7))
                            .addComponent(txtTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnVerPagos, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(btnVerFactura, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotalDeuda, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTotalDeuda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtIdCuentaCobrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7))
                            .addComponent(btnVerFactura))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(txtTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnVerPagos)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        lblUsuarioTipo.setText(resourceMap.getString("lblUsuarioTipo.text")); // NOI18N
        lblUsuarioTipo.setName("lblUsuarioTipo"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUsuarioTipo)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(lblUsuarioTipo)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public class MiModelo extends DefaultTableModel
    {
            @Override
       public boolean isCellEditable (int row, int column)
       {
           // Aquí devolvemos true o false según queramos que una celda
           // identificada por fila,columna (row,column), sea o no editable
          /* if (column == 3)
              return true;*/
           
           return false;
       }
    } 

    public class colorFilaTable extends DefaultTableCellRenderer { 
        @Override 
        public Component getTableCellRendererComponent (JTable table, Object value, boolean selected, boolean focused, int row, int column ) 
        { 
            setEnabled(table == null || table.isEnabled());        

            if(String.valueOf(table.getValueAt(row,7)).equals("NOTA DE ENTREGA")) 
                setBackground(Color.green); 
            else if(String.valueOf(table.getValueAt(row,7)).equals("FACTURA")) 
                setBackground(Color.PINK); 
            else setBackground(null); 

            super.getTableCellRendererComponent(table, value, selected, focused, row, column); 
            return this; 
        } 
    }  

    
private void tblDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataMouseClicked
     int fila = tblData.rowAtPoint(evt.getPoint());
     //int columna = tblData.columnAtPoint(evt.getPoint());
     
     txtIdCuentaCobrar.setText(""+tblData.getValueAt(fila,5));
     txtDescripcion.setText(""+tblData.getValueAt(fila,2));
     saldoActual = Double.parseDouble(""+tblData.getValueAt(fila,4));
     txtTipoDocumento.setText(""+tblData.getValueAt(fila,7));     
}//GEN-LAST:event_tblDataMouseClicked

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    objUtils.vaciarTabla(dtmData);
    frmListClientes ventana = new frmListClientes(null, true, "8");
    //new inventariopdf.JDEscoger(this, true);
    ventana.setLocationRelativeTo(null);
    ventana.setVisible(true);
}//GEN-LAST:event_jButton1ActionPerformed

private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
     llenarDataCliente();
}//GEN-LAST:event_btnBuscarClienteActionPerformed

public void llenarDataCliente()
{
    ArrayList<clsCliente> dataCliente = objCliente.consultarDataCliente(txtCedula.getText().toString());
    if(dataCliente.isEmpty())
    {
        JOptionPane.showMessageDialog(this, "Cédula no existe!!!", "Atención!", JOptionPane.ERROR_MESSAGE);
    }
    else
    {
        //objUtils.limpiarJTable(dtmData);
        this.txtNombreCliente.setText(dataCliente.get(0).getNameCompleto());
        txtDireccion.setText(dataCliente.get(0).getDireccion());
        txtTelefono.setText(dataCliente.get(0).getTlfCelular() + " - " + dataCliente.get(0).getTlfConvencional());
        if(dataCliente.get(0).getVerificadoDeudas().equals("N"))
        {
            getContentPane().setBackground(new java.awt.Color(255,0,0));
            jPanel1.setBackground(new java.awt.Color(255,0,0));
            jPanel2.setBackground(new java.awt.Color(255,0,0));   
            lblUsuarioTipo.setText("USUARIO SIN CUENTAS VERIFICADAS");
        }
        else
        {
            getContentPane().setBackground(new java.awt.Color(240,240,240));
            jPanel1.setBackground(new java.awt.Color(240,240,240));
            jPanel2.setBackground(new java.awt.Color(240,240,240));            
            lblUsuarioTipo.setText("CUENTAS VERIFICADAS CORRECTAMENTE");
        }
        //BUSCAR LAS CUENTAS POR COBRAR
        codigoCliente = "" + dataCliente.get(0).getCodigo();
        llenarTablaDeudas();
        
    }
}

    void llenarTablaDeudas()
    {
        objUtils.limpiarJTable(dtmData);
        ArrayList<clsCtasCobrar> dataCtasCobrar;
        ArrayList<clsCtasCobrar> dataCtasCobrarFact;
        ArrayList<clsCtasCobrar> dataContado;
        int i = 0;
        Double totalDeudas = 0.00;
        
        if(chkDeudasCero.isSelected())
        {
            dataCtasCobrar = objCtasCobrar.consultaCtasCobrarNotasEntrega(codigoCliente);  
            dataCtasCobrarFact = objCtasCobrar.consultaCtasCobrarFacturas(codigoCliente); 
        }
        else
        {
            dataCtasCobrar = objCtasCobrar.consultaCtasCobrarNotasEntregaConSaldo(codigoCliente); 
            dataCtasCobrarFact = objCtasCobrar.consultaCtasCobrarFacturasConSaldo(codigoCliente); 
        }
        Double valor;
        Double valorActual;
        int maxData = dataCtasCobrar.size();
        int maxDataFact = dataCtasCobrarFact.size();
        //SI ESCOJE AQUI MUESTRO LAS NOTAS DE ENTREGA A CONTADO
        if(chkContado.isSelected())
        {
            dataContado = objCtasCobrar.consultaNotasEntregaContado(codigoCliente); 
            int maxDataContado = dataContado.size();
            for(int k = 0; k<maxDataContado; k++)
            {
                 valor = Double.parseDouble(dataContado.get(k).getValor());
                 valorActual = Double.parseDouble(dataContado.get(k).getValorActual());

                 Object[] nuevaFila = {i+1, 
                                        dataContado.get(k).getFactReferencia(), 
                                        dataContado.get(k).getDescripcion(), 
                                        objUtils.redondear(valor), 
                                        objUtils.redondear(valorActual),
                                        dataContado.get(k).getIdCtaCobrar(),
                                        dataContado.get(k).getIdCabeceraMovi(),
                                        "NOTA DE ENTREGA"};
                 dtmData.addRow(nuevaFila); 
                 i++;
            }   
        }
        if((maxData==0)&&(maxDataFact==0))
        {
            JOptionPane.showMessageDialog(this, "No tiene cuentas por cobrar", "Atención!", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
           
            for(i=0;i<maxData;i++)
            {
                 valor = Double.parseDouble(dataCtasCobrar.get(i).getValor());
                 valorActual = Double.parseDouble(dataCtasCobrar.get(i).getValorActual());

                 Object[] nuevaFila = {i+1, 
                                        dataCtasCobrar.get(i).getFactReferencia(), 
                                        dataCtasCobrar.get(i).getDescripcion(), 
                                        objUtils.redondear(valor), 
                                        objUtils.redondear(valorActual),
                                        dataCtasCobrar.get(i).getIdCtaCobrar(),
                                        dataCtasCobrar.get(i).getIdCabeceraMovi(),
                                        "NOTA DE ENTREGA"};
                 dtmData.addRow(nuevaFila); 
                 totalDeudas = totalDeudas + valorActual;
            }   
            
            for(int j=0;j<maxDataFact;j++)
            {
                 valor = Double.parseDouble(dataCtasCobrarFact.get(j).getValor());
                 valorActual = Double.parseDouble(dataCtasCobrarFact.get(j).getValorActual());

                 Object[] nuevaFila = {i+1, 
                                        dataCtasCobrarFact.get(j).getFactReferencia(), 
                                        dataCtasCobrarFact.get(j).getDescripcion(), 
                                        objUtils.redondear(valor), 
                                        objUtils.redondear(valorActual),
                                        dataCtasCobrarFact.get(j).getIdCtaCobrar(),
                                        dataCtasCobrarFact.get(j).getIdCabeceraMovi(),
                                        "FACTURA"};
                 dtmData.addRow(nuevaFila); 
                 i++;
                 totalDeudas = totalDeudas + valorActual;
            }   
        }
        this.txtTotalDeuda.setText("" + objUtils.redondear(totalDeudas));        
    }

private void btnVerFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerFacturaActionPerformed
    int i = tblData.getSelectedRow();
    if(i<0)
    {
        JOptionPane.showMessageDialog(this, "No ha seleccionado ninguna factura", "Atención", JOptionPane.ERROR_MESSAGE);
    }
    else
    {
        if(tblData.getValueAt(i,7).equals("NOTA DE ENTREGA"))
        {   
            int idCabecera = Integer.parseInt(""+tblData.getValueAt(i,6));
            System.out.println(idCabecera);
            frmFactHistoShow ventana = new frmFactHistoShow(null, true, idCabecera);
            ventana.setLocationRelativeTo(null);
            ventana.setVisible(true);
        }
        else if(tblData.getValueAt(i,7).equals("FACTURA"))
        {
            String idCabecera = ""+tblData.getValueAt(i,6);
            System.out.println(idCabecera);
            frmFactDeudaShow ventana = new frmFactDeudaShow(null, true, idCabecera);
            ventana.setLocationRelativeTo(null);
            ventana.setVisible(true);
        }
    }
}//GEN-LAST:event_btnVerFacturaActionPerformed

private void btnVerPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerPagosActionPerformed
    int i = tblData.getSelectedRow();
    if(i<0)
    {
        JOptionPane.showMessageDialog(this, "No ha seleccionado ninguna factura", "Atención", JOptionPane.ERROR_MESSAGE);
    }
    else
    {
        if(tblData.getValueAt(i,7).equals("NOTA DE ENTREGA"))
        {   
            int idCabecera = Integer.parseInt(""+tblData.getValueAt(i,6));
            objReporte.ejecutarReporteParametroInt(idCabecera, "rptPagosFactura");
        }
        else if(tblData.getValueAt(i,7).equals("FACTURA"))
        {
           int idCabecera = Integer.parseInt(""+tblData.getValueAt(i,6));
           objReporte.ejecutarReporteParametroInt(idCabecera, "rptPagosFacturaCredito");
        }
        
    }
}//GEN-LAST:event_btnVerPagosActionPerformed

private void txtCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyTyped
    if(evt.getKeyChar() == KeyEvent.VK_ENTER){
            //KeyboardFocusManager manager = KeyboardFocusManager.getCurrentKeyboardFocusManager();
            //manager.focusNextComponent(); 
        this.llenarDataCliente();
    }
}//GEN-LAST:event_txtCedulaKeyTyped

private void chkDeudasCeroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkDeudasCeroItemStateChanged
    //llenarDataCliente();  
}//GEN-LAST:event_chkDeudasCeroItemStateChanged

private void chkContadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkContadoItemStateChanged
    //llenarDataCliente();     
}//GEN-LAST:event_chkContadoItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnVerFactura;
    private javax.swing.JButton btnVerPagos;
    private javax.swing.JCheckBox chkContado;
    private javax.swing.JCheckBox chkDeudasCero;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblUsuarioTipo;
    private javax.swing.JTable tblData;
    public static javax.swing.JTextField txtCedula;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtIdCuentaCobrar;
    public static javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTipoDocumento;
    private javax.swing.JTextField txtTotalDeuda;
    // End of variables declaration//GEN-END:variables
}
