/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmUsuarioPermisos.java
 *
 * Created on 28/10/2011, 09:42:45 AM
 */
package usuarios;

import clases.clsAuditoria;
import clases.clsComboBox;
import clases.clsPermisos;
import java.util.ArrayList;
import clases.clsUsuario;
import javax.swing.JOptionPane;

/**
 *
 * @author CKaiser
 */
public class frmUsuarioPermisos extends javax.swing.JInternalFrame {
    clsUsuario objUsuario = new clsUsuario();
    clsPermisos objPermisos = new clsPermisos();
    clsAuditoria objAuditoria = new clsAuditoria();
    /** Creates new form frmUsuarioPermisos */
    public frmUsuarioPermisos() {
        initComponents();
        
        //CARGAR USUARIOS
        ArrayList<clsComboBox> dataUsuario = objUsuario.consultarUsuarios();        
        for(int i=0;i<dataUsuario.size();i=i+1)
        {
            clsComboBox oItem = new clsComboBox(dataUsuario.get(i).getCodigo(), dataUsuario.get(i).getDescripcion());
            cmbUsuarios.addItem(oItem);            
        }
    }
    
    void vaciarPermisos()
    {
        chkAbrirCaja.setSelected(false);
        chkCerrarCaja.setSelected(false);
        chkFacturar.setSelected(false);
        chkPermisos.setSelected(false);
        chkCreacionUsuario.setSelected(false);
        chkModificarProductos.setSelected(false);
        chkPagos.setSelected(false);
        chkPagosHistorico.setSelected(false);
        chkFactHistorico.setSelected(false);
        chkEliminarProductos.setSelected(false);
        chkKardex.setSelected(false);
        chkRecibir.setSelected(false);
        chkRetirar.setSelected(false);
        chkMantenimientoGrupo.setSelected(false);
        chkAnularFacturas.setSelected(false);
        chkFlujo.setSelected(false);
        chkListProductosDel.setSelected(false);
        chkEliminarPagos.setSelected(false);
        chkNotasEntrega.setSelected(false);
        chkAuditoria.setSelected(false);
        chkVentaCaja.setSelected(false);
        chkVentasNE.setSelected(false);
        chkVentasNEVendedores.setSelected(false);
        chkDescuentos.setSelected(false);
        chkModClientes.setSelected(false);
        chkClienteDel.setSelected(false);
        chkProveedorMod.setSelected(false);
        chkProveedorDel.setSelected(false);
        chkChequear.setSelected(false);
        chkRepPagos.setSelected(false);
        chkInventario.setSelected(false);
        chkPagoNuevo.setSelected(false);
        chkPagoRecibo.setSelected(false);
        chkAddCliente.setSelected(false);
        chkReimpresion.setSelected(false);
        chkRecibirCompras.setSelected(false);
    }
    /** This method fis called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbUsuarios = new javax.swing.JComboBox();
        btnGuardar = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jideTabbedPane1 = new com.jidesoft.swing.JideTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        chkPermisos = new javax.swing.JCheckBox();
        chkCreacionUsuario = new javax.swing.JCheckBox();
        chkAuditoria = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        chkAbrirCaja = new javax.swing.JCheckBox();
        chkCerrarCaja = new javax.swing.JCheckBox();
        chkFacturar = new javax.swing.JCheckBox();
        chkPagos = new javax.swing.JCheckBox();
        chkAnularFacturas = new javax.swing.JCheckBox();
        chkFlujo = new javax.swing.JCheckBox();
        chkEliminarPagos = new javax.swing.JCheckBox();
        chkNotasEntrega = new javax.swing.JCheckBox();
        chkPagoNuevo = new javax.swing.JCheckBox();
        chkPagoRecibo = new javax.swing.JCheckBox();
        chkReimpresion = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        chkPagosHistorico = new javax.swing.JCheckBox();
        chkFactHistorico = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        chkModificarProductos = new javax.swing.JCheckBox();
        chkEliminarProductos = new javax.swing.JCheckBox();
        chkKardex = new javax.swing.JCheckBox();
        chkRecibir = new javax.swing.JCheckBox();
        chkRetirar = new javax.swing.JCheckBox();
        chkListProductosDel = new javax.swing.JCheckBox();
        chkChequear = new javax.swing.JCheckBox();
        chkInventario = new javax.swing.JCheckBox();
        chkRecibirCompras = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        chkMantenimientoGrupo = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        chkVentaCaja = new javax.swing.JCheckBox();
        chkVentasNE = new javax.swing.JCheckBox();
        chkVentasNEVendedores = new javax.swing.JCheckBox();
        chkDescuentos = new javax.swing.JCheckBox();
        chkRepPagos = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        chkModClientes = new javax.swing.JCheckBox();
        chkClienteDel = new javax.swing.JCheckBox();
        chkAddCliente = new javax.swing.JCheckBox();
        jPanel8 = new javax.swing.JPanel();
        chkProveedorMod = new javax.swing.JCheckBox();
        chkProveedorDel = new javax.swing.JCheckBox();

        setClosable(true);
        setIconifiable(true);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(stinventario.STInventarioApp.class).getContext().getResourceMap(frmUsuarioPermisos.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        cmbUsuarios.setName("cmbUsuarios"); // NOI18N
        cmbUsuarios.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbUsuariosItemStateChanged(evt);
            }
        });

        btnGuardar.setText(resourceMap.getString("btnGuardar.text")); // NOI18N
        btnGuardar.setEnabled(false);
        btnGuardar.setName("btnGuardar"); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnMostrar.setText(resourceMap.getString("btnMostrar.text")); // NOI18N
        btnMostrar.setName("btnMostrar"); // NOI18N
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jideTabbedPane1.setBorder(null);
        jideTabbedPane1.setName("jideTabbedPane1"); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setEnabled(false);
        jPanel2.setName("jPanel2"); // NOI18N

        chkPermisos.setText(resourceMap.getString("chkPermisos.text")); // NOI18N
        chkPermisos.setEnabled(false);
        chkPermisos.setName("chkPermisos"); // NOI18N

        chkCreacionUsuario.setText(resourceMap.getString("chkCreacionUsuario.text")); // NOI18N
        chkCreacionUsuario.setEnabled(false);
        chkCreacionUsuario.setName("chkCreacionUsuario"); // NOI18N

        chkAuditoria.setText(resourceMap.getString("chkAuditoria.text")); // NOI18N
        chkAuditoria.setEnabled(false);
        chkAuditoria.setName("chkAuditoria"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkPermisos)
                    .addComponent(chkCreacionUsuario)
                    .addComponent(chkAuditoria))
                .addContainerGap(492, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chkPermisos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkCreacionUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkAuditoria)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        jideTabbedPane1.addTab(resourceMap.getString("jPanel2.TabConstraints.tabTitle"), jPanel2); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setName("jPanel1"); // NOI18N

        chkAbrirCaja.setText(resourceMap.getString("chkAbrirCaja.text")); // NOI18N
        chkAbrirCaja.setName("chkAbrirCaja"); // NOI18N

        chkCerrarCaja.setText(resourceMap.getString("chkCerrarCaja.text")); // NOI18N
        chkCerrarCaja.setName("chkCerrarCaja"); // NOI18N

        chkFacturar.setText(resourceMap.getString("chkFacturar.text")); // NOI18N
        chkFacturar.setName("chkFacturar"); // NOI18N

        chkPagos.setText(resourceMap.getString("chkPagos.text")); // NOI18N
        chkPagos.setName("chkPagos"); // NOI18N
        chkPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkPagosActionPerformed(evt);
            }
        });

        chkAnularFacturas.setText(resourceMap.getString("chkAnularFacturas.text")); // NOI18N
        chkAnularFacturas.setName("chkAnularFacturas"); // NOI18N

        chkFlujo.setText(resourceMap.getString("chkFlujo.text")); // NOI18N
        chkFlujo.setName("chkFlujo"); // NOI18N

        chkEliminarPagos.setText(resourceMap.getString("chkEliminarPagos.text")); // NOI18N
        chkEliminarPagos.setName("chkEliminarPagos"); // NOI18N

        chkNotasEntrega.setText(resourceMap.getString("chkNotasEntrega.text")); // NOI18N
        chkNotasEntrega.setName("chkNotasEntrega"); // NOI18N

        chkPagoNuevo.setText(resourceMap.getString("chkPagoNuevo.text")); // NOI18N
        chkPagoNuevo.setName("chkPagoNuevo"); // NOI18N

        chkPagoRecibo.setText(resourceMap.getString("chkPagoRecibo.text")); // NOI18N
        chkPagoRecibo.setName("chkPagoRecibo"); // NOI18N

        chkReimpresion.setText(resourceMap.getString("chkReimpresion.text")); // NOI18N
        chkReimpresion.setName("chkReimpresion"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkAbrirCaja)
                    .addComponent(chkCerrarCaja)
                    .addComponent(chkFacturar)
                    .addComponent(chkPagos)
                    .addComponent(chkPagoNuevo))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkPagoRecibo)
                    .addComponent(chkNotasEntrega)
                    .addComponent(chkEliminarPagos)
                    .addComponent(chkFlujo)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(chkAnularFacturas)
                        .addGap(108, 108, 108)
                        .addComponent(chkReimpresion)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkAbrirCaja)
                    .addComponent(chkAnularFacturas)
                    .addComponent(chkReimpresion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkCerrarCaja)
                    .addComponent(chkFlujo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkFacturar)
                    .addComponent(chkEliminarPagos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkPagos)
                    .addComponent(chkNotasEntrega))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkPagoNuevo)
                    .addComponent(chkPagoRecibo))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jideTabbedPane1.addTab(resourceMap.getString("jPanel1.TabConstraints.tabTitle"), jPanel1); // NOI18N

        jPanel3.setName("jPanel3"); // NOI18N

        chkPagosHistorico.setText(resourceMap.getString("chkPagosHistorico.text")); // NOI18N
        chkPagosHistorico.setName("chkPagosHistorico"); // NOI18N

        chkFactHistorico.setText(resourceMap.getString("chkFactHistorico.text")); // NOI18N
        chkFactHistorico.setName("chkFactHistorico"); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkFactHistorico)
                    .addComponent(chkPagosHistorico))
                .addContainerGap(447, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(chkFactHistorico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkPagosHistorico)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        jideTabbedPane1.addTab(resourceMap.getString("jPanel3.TabConstraints.tabTitle"), jPanel3); // NOI18N

        jPanel4.setName("jPanel4"); // NOI18N

        chkModificarProductos.setText(resourceMap.getString("chkModificarProductos.text")); // NOI18N
        chkModificarProductos.setName("chkModificarProductos"); // NOI18N

        chkEliminarProductos.setText(resourceMap.getString("chkEliminarProductos.text")); // NOI18N
        chkEliminarProductos.setName("chkEliminarProductos"); // NOI18N

        chkKardex.setText(resourceMap.getString("chkKardex.text")); // NOI18N
        chkKardex.setName("chkKardex"); // NOI18N
        chkKardex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkKardexActionPerformed(evt);
            }
        });

        chkRecibir.setText(resourceMap.getString("chkRecibir.text")); // NOI18N
        chkRecibir.setName("chkRecibir"); // NOI18N

        chkRetirar.setText(resourceMap.getString("chkRetirar.text")); // NOI18N
        chkRetirar.setName("chkRetirar"); // NOI18N

        chkListProductosDel.setText(resourceMap.getString("chkListProductosDel.text")); // NOI18N
        chkListProductosDel.setName("chkListProductosDel"); // NOI18N

        chkChequear.setText(resourceMap.getString("chkChequear.text")); // NOI18N
        chkChequear.setName("chkChequear"); // NOI18N

        chkInventario.setText(resourceMap.getString("chkInventario.text")); // NOI18N
        chkInventario.setName("chkInventario"); // NOI18N

        chkRecibirCompras.setText(resourceMap.getString("chkRecibirCompras.text")); // NOI18N
        chkRecibirCompras.setName("chkRecibirCompras"); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkRetirar)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkModificarProductos)
                            .addComponent(chkEliminarProductos)
                            .addComponent(chkKardex)
                            .addComponent(chkRecibir))
                        .addGap(55, 55, 55)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkRecibirCompras)
                            .addComponent(chkInventario)
                            .addComponent(chkChequear)
                            .addComponent(chkListProductosDel))))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkModificarProductos)
                    .addComponent(chkListProductosDel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkEliminarProductos)
                    .addComponent(chkChequear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkKardex)
                    .addComponent(chkInventario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkRecibir)
                    .addComponent(chkRecibirCompras))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkRetirar)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jideTabbedPane1.addTab(resourceMap.getString("jPanel4.TabConstraints.tabTitle"), jPanel4); // NOI18N

        jPanel5.setName("jPanel5"); // NOI18N

        chkMantenimientoGrupo.setText(resourceMap.getString("chkMantenimientoGrupo.text")); // NOI18N
        chkMantenimientoGrupo.setName("chkMantenimientoGrupo"); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(chkMantenimientoGrupo)
                .addContainerGap(392, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(chkMantenimientoGrupo)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        jideTabbedPane1.addTab(resourceMap.getString("jPanel5.TabConstraints.tabTitle"), jPanel5); // NOI18N

        jPanel7.setName("jPanel7"); // NOI18N

        chkVentaCaja.setText(resourceMap.getString("chkVentaCaja.text")); // NOI18N
        chkVentaCaja.setName("chkVentaCaja"); // NOI18N

        chkVentasNE.setText(resourceMap.getString("chkVentasNE.text")); // NOI18N
        chkVentasNE.setName("chkVentasNE"); // NOI18N

        chkVentasNEVendedores.setText(resourceMap.getString("chkVentasNEVendedores.text")); // NOI18N
        chkVentasNEVendedores.setName("chkVentasNEVendedores"); // NOI18N

        chkDescuentos.setText(resourceMap.getString("chkDescuentos.text")); // NOI18N
        chkDescuentos.setName("chkDescuentos"); // NOI18N

        chkRepPagos.setText(resourceMap.getString("chkRepPagos.text")); // NOI18N
        chkRepPagos.setName("chkRepPagos"); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(chkVentaCaja)
                        .addGap(69, 69, 69)
                        .addComponent(chkRepPagos))
                    .addComponent(chkVentasNEVendedores)
                    .addComponent(chkVentasNE)
                    .addComponent(chkDescuentos))
                .addContainerGap(251, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkVentaCaja)
                    .addComponent(chkRepPagos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkVentasNE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkVentasNEVendedores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkDescuentos)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jideTabbedPane1.addTab(resourceMap.getString("jPanel7.TabConstraints.tabTitle"), jPanel7); // NOI18N

        jPanel6.setName("jPanel6"); // NOI18N

        chkModClientes.setText(resourceMap.getString("chkModClientes.text")); // NOI18N
        chkModClientes.setName("chkModClientes"); // NOI18N

        chkClienteDel.setText(resourceMap.getString("chkClienteDel.text")); // NOI18N
        chkClienteDel.setName("chkClienteDel"); // NOI18N

        chkAddCliente.setText(resourceMap.getString("chkAddCliente.text")); // NOI18N
        chkAddCliente.setName("chkAddCliente"); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkAddCliente)
                    .addComponent(chkClienteDel)
                    .addComponent(chkModClientes))
                .addContainerGap(490, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(chkModClientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkClienteDel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkAddCliente)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        jideTabbedPane1.addTab(resourceMap.getString("jPanel6.TabConstraints.tabTitle"), jPanel6); // NOI18N

        jPanel8.setName("jPanel8"); // NOI18N

        chkProveedorMod.setText(resourceMap.getString("chkProveedorMod.text")); // NOI18N
        chkProveedorMod.setName("chkProveedorMod"); // NOI18N

        chkProveedorDel.setText(resourceMap.getString("chkProveedorDel.text")); // NOI18N
        chkProveedorDel.setName("chkProveedorDel"); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkProveedorDel)
                    .addComponent(chkProveedorMod))
                .addContainerGap(488, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(chkProveedorMod)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkProveedorDel)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        jideTabbedPane1.addTab(resourceMap.getString("jPanel8.TabConstraints.tabTitle"), jPanel8); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(btnGuardar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnMostrar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jideTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnMostrar))
                .addGap(30, 30, 30)
                .addComponent(jideTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardar)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String idModulo="";
        String idFormulario="";
        clsComboBox objUsuarioSelect = (clsComboBox)cmbUsuarios.getSelectedItem();
        //ELIMINAR PERMISOS ACTUALES
        objPermisos.eliminarPermisos(objUsuarioSelect.getCodigo());
         //GUARDAR LOS NUEVOS
        if(this.chkAbrirCaja.isSelected())
        {
            idModulo = "1";
            idFormulario = "2";
            objPermisos.insertarRegistro(objUsuarioSelect.getCodigo(), idModulo, idFormulario);
        }
        if(this.chkCerrarCaja.isSelected())
        {
            idModulo = "1";
            idFormulario = "3";
            objPermisos.insertarRegistro(objUsuarioSelect.getCodigo(), idModulo, idFormulario);
        }
        if(this.chkFacturar.isSelected())
        {
            idModulo = "1";
            idFormulario = "4";
            objPermisos.insertarRegistro(objUsuarioSelect.getCodigo(), idModulo, idFormulario);
        }
        if(this.chkPermisos.isSelected())
        {
            idModulo = "3";
            idFormulario = "5";
            objPermisos.insertarRegistro(objUsuarioSelect.getCodigo(), idModulo, idFormulario);
        }
        if(this.chkCreacionUsuario.isSelected())
        {
            idModulo = "3";
            idFormulario = "14";
            objPermisos.insertarRegistro(objUsuarioSelect.getCodigo(), idModulo, idFormulario);
        }
        if(this.chkModificarProductos.isSelected())
        {
            idModulo = "3";
            idFormulario = "6";
            objPermisos.insertarRegistro(objUsuarioSelect.getCodigo(), idModulo, idFormulario);
        }
        if(this.chkPagos.isSelected())
        {
            idModulo = "1";
            idFormulario = "7";
            objPermisos.insertarRegistro(objUsuarioSelect.getCodigo(), idModulo, idFormulario);
        }
        if(this.chkPagosHistorico.isSelected())
        {
            idModulo = "1";
            idFormulario = "8";
            objPermisos.insertarRegistro(objUsuarioSelect.getCodigo(), idModulo, idFormulario);
        }
        if(this.chkFactHistorico.isSelected())
        {
            idModulo = "1";
            idFormulario = "9";
            objPermisos.insertarRegistro(objUsuarioSelect.getCodigo(), idModulo, idFormulario);
        }
        if(this.chkEliminarProductos.isSelected())
        {
            idModulo = "1";
            idFormulario = "10";
            objPermisos.insertarRegistro(objUsuarioSelect.getCodigo(), idModulo, idFormulario);
        }
        if(this.chkKardex.isSelected())
        {
            idModulo = "2";
            idFormulario = "11";
            objPermisos.insertarRegistro(objUsuarioSelect.getCodigo(), idModulo, idFormulario);
        }
        if(this.chkRecibir.isSelected())
        {
            idModulo = "2";
            idFormulario = "12";
            objPermisos.insertarRegistro(objUsuarioSelect.getCodigo(), idModulo, idFormulario);
        }
        if(this.chkRetirar.isSelected())
        {
            idModulo = "2";
            idFormulario = "13";
            objPermisos.insertarRegistro(objUsuarioSelect.getCodigo(), idModulo, idFormulario);
        }
        if(this.chkMantenimientoGrupo.isSelected())
        {
            idModulo = "2";
            idFormulario = "15";
            objPermisos.insertarRegistro(objUsuarioSelect.getCodigo(), idModulo, idFormulario);
        }
        if(this.chkAnularFacturas.isSelected())
        {
            idModulo = "1";
            idFormulario = "16";
            objPermisos.insertarRegistro(objUsuarioSelect.getCodigo(), idModulo, idFormulario);
        }
        if(this.chkFlujo.isSelected())
        {
            idModulo = "1";
            idFormulario = "17";
            objPermisos.insertarRegistro(objUsuarioSelect.getCodigo(), idModulo, idFormulario);
        }
        if(this.chkListProductosDel.isSelected())
        {
            idModulo = "1";
            idFormulario = "18";
            objPermisos.insertarRegistro(objUsuarioSelect.getCodigo(), idModulo, idFormulario);
        }  
        if(this.chkEliminarPagos.isSelected())
        {
            idModulo = "1";
            idFormulario = "19";
            objPermisos.insertarRegistro(objUsuarioSelect.getCodigo(), idModulo, idFormulario);
        }  
        if(this.chkNotasEntrega.isSelected())
        {
            idModulo = "1";
            idFormulario = "20";
            objPermisos.insertarRegistro(objUsuarioSelect.getCodigo(), idModulo, idFormulario);
        }  
        if(this.chkAuditoria.isSelected())
        {
            idModulo = "1";
            idFormulario = "21";
            objPermisos.insertarRegistro(objUsuarioSelect.getCodigo(), idModulo, idFormulario);
        }  
        if(this.chkVentaCaja.isSelected())
        {
            idModulo = "1";
            idFormulario = "22";
            objPermisos.insertarRegistro(objUsuarioSelect.getCodigo(), idModulo, idFormulario);
        } 
        if(this.chkVentasNE.isSelected())
        {
            idModulo = "1";
            idFormulario = "23";
            objPermisos.insertarRegistro(objUsuarioSelect.getCodigo(), idModulo, idFormulario);
        } 
        if(this.chkVentasNEVendedores.isSelected())
        {
            idModulo = "1";
            idFormulario = "24";
            objPermisos.insertarRegistro(objUsuarioSelect.getCodigo(), idModulo, idFormulario);
        }
        if(this.chkDescuentos.isSelected())
        {
            idModulo = "1";
            idFormulario = "25";
            objPermisos.insertarRegistro(objUsuarioSelect.getCodigo(), idModulo, idFormulario);
        }
        if(this.chkModClientes.isSelected())
        {
            idModulo = "1";
            idFormulario = "26";
            objPermisos.insertarRegistro(objUsuarioSelect.getCodigo(), idModulo, idFormulario);
        }
        if(this.chkClienteDel.isSelected())
        {
            idModulo = "1";
            idFormulario = "27";
            objPermisos.insertarRegistro(objUsuarioSelect.getCodigo(), idModulo, idFormulario);
        }
        if(this.chkProveedorMod.isSelected())
        {
            idModulo = "1";
            idFormulario = "28";
            objPermisos.insertarRegistro(objUsuarioSelect.getCodigo(), idModulo, idFormulario);
        }
        if(this.chkProveedorDel.isSelected())
        {
            idModulo = "1";
            idFormulario = "29";
            objPermisos.insertarRegistro(objUsuarioSelect.getCodigo(), idModulo, idFormulario);
        }
        if(this.chkChequear.isSelected())
        {
            idModulo = "1";
            idFormulario = "30";
            objPermisos.insertarRegistro(objUsuarioSelect.getCodigo(), idModulo, idFormulario);
        }
        if(this.chkRepPagos.isSelected())
        {
            idModulo = "1";
            idFormulario = "31";
            objPermisos.insertarRegistro(objUsuarioSelect.getCodigo(), idModulo, idFormulario);
        }
        if(this.chkInventario.isSelected())
        {
            idModulo = "1";
            idFormulario = "32";
            objPermisos.insertarRegistro(objUsuarioSelect.getCodigo(), idModulo, idFormulario);
        }
        if(this.chkPagoNuevo.isSelected())
        {
            idModulo = "1";
            idFormulario = "33";
            objPermisos.insertarRegistro(objUsuarioSelect.getCodigo(), idModulo, idFormulario);
        }
        if(this.chkPagoRecibo.isSelected())
        {
            idModulo = "1";
            idFormulario = "34";
            objPermisos.insertarRegistro(objUsuarioSelect.getCodigo(), idModulo, idFormulario);
        }
        if(this.chkAddCliente.isSelected())
        {
            idModulo = "1";
            idFormulario = "35";
            objPermisos.insertarRegistro(objUsuarioSelect.getCodigo(), idModulo, idFormulario);
        }
        if(this.chkReimpresion.isSelected())
        {
            idModulo = "1";
            idFormulario = "36";
            objPermisos.insertarRegistro(objUsuarioSelect.getCodigo(), idModulo, idFormulario);
        }
        if(this.chkRecibirCompras.isSelected())
        {
            idModulo = "1";
            idFormulario = "37";
            objPermisos.insertarRegistro(objUsuarioSelect.getCodigo(), idModulo, idFormulario);
        }
        
        
        objAuditoria.insertarAuditoria("frmUsuarioPermisos", "CAMBIO DE PERMISOS AL USUARIO:" + objUsuarioSelect.getDescripcion(), "4");
        JOptionPane.showMessageDialog(this, "Datos almacenados con éxito", "Atención!", JOptionPane.INFORMATION_MESSAGE);
        vaciarPermisos(); 
        reinicio();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        //BUSCAR PERMISOS
        vaciarPermisos();
        
        jideTabbedPane1.setEnabled(true);
        jPanel2.setEnabled(true);
        chkPermisos.setEnabled(true);
        chkCreacionUsuario.setEnabled(true);
        chkAuditoria.setEnabled(true);
        
        String nombreFormulario = "";
        clsComboBox objUsuarioSelect = (clsComboBox)cmbUsuarios.getSelectedItem();
        ArrayList<clsPermisos> dataPermisos = objPermisos.consultarPermisosUsuario(Integer.parseInt(objUsuarioSelect.getCodigo()));        
        for(int i=0;i<dataPermisos.size();i=i+1)
        {
            nombreFormulario = dataPermisos.get(i).getFormDescripcion();
            if(nombreFormulario.equals("frmAbrirCaja"))
            {
                chkAbrirCaja.setSelected(true);
            }
            if(nombreFormulario.equals("frmCerrarCaja"))
            {
                chkCerrarCaja.setSelected(true);
            }
            if(nombreFormulario.equals("frmFacturar"))
            {
                chkFacturar.setSelected(true);
            }   
            if(nombreFormulario.equals("frmUsuarioPermisos"))
            {
                chkPermisos.setSelected(true);
            }  
            if(nombreFormulario.equals("frmNuevoUsuario"))
            {
                chkCreacionUsuario.setSelected(true);
            } 
            if(nombreFormulario.equals("frmProductosMod"))
            {
                chkModificarProductos.setSelected(true);
            }  
            if(nombreFormulario.equals("frmPagoAdd"))
            {
                chkPagos.setSelected(true);
            } 
            if(nombreFormulario.equals("frmPagoHistoricoAdd"))
            {
                chkPagosHistorico.setSelected(true);
            } 
            if(nombreFormulario.equals("frmFactHisto"))
            {
                chkFactHistorico.setSelected(true);
            } 
            if(nombreFormulario.equals("frmProductosDel"))
            {
                chkEliminarProductos.setSelected(true);
            } 
            if(nombreFormulario.equals("frmKardex"))
            {
                chkKardex.setSelected(true);
            } 
            if(nombreFormulario.equals("frmKardexIngreso"))
            {
                chkRecibir.setSelected(true);
            } 
            if(nombreFormulario.equals("frmKardexEgreso"))
            {
                chkRetirar.setSelected(true);
            } 
            if(nombreFormulario.equals("frmGrupoAdd"))
            {
                chkMantenimientoGrupo.setSelected(true);
            } 
            if(nombreFormulario.equals("frmFacturaSeek"))
            {
                chkAnularFacturas.setSelected(true);
            } 
            if(nombreFormulario.equals("frmCerrarCaja_"))
            {
                chkFlujo.setSelected(true);
            } 
            if(nombreFormulario.equals("frmListProductosDel"))
            {
                chkListProductosDel.setSelected(true);
            } 
            if(nombreFormulario.equals("frmPagosEliminar"))
            {
                chkEliminarPagos.setSelected(true);
            } 
            if(nombreFormulario.equals("frmNotasEntrega"))
            {
                chkNotasEntrega.setSelected(true);
            } 
            if(nombreFormulario.equals("frmAuditoria"))
            {
                chkAuditoria.setSelected(true);
            } 
            if(nombreFormulario.equals("frmListVentas"))
            {
                chkVentaCaja.setSelected(true);
            } 
            if(nombreFormulario.equals("frmListVentasNE"))
            {
                chkVentasNE.setSelected(true);
            } 
            if(nombreFormulario.equals("frmListVentasNEVendedor"))
            {
                chkVentasNEVendedores.setSelected(true);
            } 
            if(nombreFormulario.equals("frmListDescuentos"))
            {
                chkDescuentos.setSelected(true);
            } 
            if(nombreFormulario.equals("frmClienteMod"))
            {
                chkModClientes.setSelected(true);
            } 
            if(nombreFormulario.equals("frmClienteDel"))
            {
                chkClienteDel.setSelected(true);
            } 
            if(nombreFormulario.equals("frmProveedorMod"))
            {
                chkProveedorMod.setSelected(true);
            } 
            if(nombreFormulario.equals("frmProveedorDel"))
            {
                chkProveedorDel.setSelected(true);
            } 
            if(nombreFormulario.equals("frmListProductosInventario"))
            {
                chkChequear.setSelected(true);
            } 
            if(nombreFormulario.equals("frmListPagos"))
            {
                chkRepPagos.setSelected(true);
            } 
            if(nombreFormulario.equals("frmInventario"))
            {
                chkInventario.setSelected(true);
            } 
            if(nombreFormulario.equals("frmPagoNuevoAdd"))
            {
                chkPagoNuevo.setSelected(true);
            } 
            if(nombreFormulario.equals("frmPagoAddOtros"))
            {
                chkPagoRecibo.setSelected(true);
            } 
            if(nombreFormulario.equals("frmClienteAdd"))
            {
                chkAddCliente.setSelected(true);
            } 
            if(nombreFormulario.equals("frmReimpresionReciboPago"))
            {
                chkReimpresion.setSelected(true);
            } 
            if(nombreFormulario.equals("frmComprasRecibir"))
            {
                chkRecibirCompras.setSelected(true);
            } 
        }
        this.btnGuardar.setEnabled(true);
    }//GEN-LAST:event_btnMostrarActionPerformed

private void chkPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPagosActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_chkPagosActionPerformed

private void chkKardexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkKardexActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_chkKardexActionPerformed

private void cmbUsuariosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbUsuariosItemStateChanged
    reinicio();
}//GEN-LAST:event_cmbUsuariosItemStateChanged

public void reinicio()
{
    jideTabbedPane1.setEnabled(false);
    jideTabbedPane1.setSelectedComponent(jPanel2);
    jPanel2.setEnabled(false);
    chkPermisos.setEnabled(false);
    chkCreacionUsuario.setEnabled(false);
    chkAuditoria.setEnabled(false);
    this.btnGuardar.setEnabled(false);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JCheckBox chkAbrirCaja;
    private javax.swing.JCheckBox chkAddCliente;
    private javax.swing.JCheckBox chkAnularFacturas;
    private javax.swing.JCheckBox chkAuditoria;
    private javax.swing.JCheckBox chkCerrarCaja;
    private javax.swing.JCheckBox chkChequear;
    private javax.swing.JCheckBox chkClienteDel;
    private javax.swing.JCheckBox chkCreacionUsuario;
    private javax.swing.JCheckBox chkDescuentos;
    private javax.swing.JCheckBox chkEliminarPagos;
    private javax.swing.JCheckBox chkEliminarProductos;
    private javax.swing.JCheckBox chkFactHistorico;
    private javax.swing.JCheckBox chkFacturar;
    private javax.swing.JCheckBox chkFlujo;
    private javax.swing.JCheckBox chkInventario;
    private javax.swing.JCheckBox chkKardex;
    private javax.swing.JCheckBox chkListProductosDel;
    private javax.swing.JCheckBox chkMantenimientoGrupo;
    private javax.swing.JCheckBox chkModClientes;
    private javax.swing.JCheckBox chkModificarProductos;
    private javax.swing.JCheckBox chkNotasEntrega;
    private javax.swing.JCheckBox chkPagoNuevo;
    private javax.swing.JCheckBox chkPagoRecibo;
    private javax.swing.JCheckBox chkPagos;
    private javax.swing.JCheckBox chkPagosHistorico;
    private javax.swing.JCheckBox chkPermisos;
    private javax.swing.JCheckBox chkProveedorDel;
    private javax.swing.JCheckBox chkProveedorMod;
    private javax.swing.JCheckBox chkRecibir;
    private javax.swing.JCheckBox chkRecibirCompras;
    private javax.swing.JCheckBox chkReimpresion;
    private javax.swing.JCheckBox chkRepPagos;
    private javax.swing.JCheckBox chkRetirar;
    private javax.swing.JCheckBox chkVentaCaja;
    private javax.swing.JCheckBox chkVentasNE;
    private javax.swing.JCheckBox chkVentasNEVendedores;
    private javax.swing.JComboBox cmbUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private com.jidesoft.swing.JideTabbedPane jideTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
