/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmPagosDeuda.java
 *
 * Created on 17/05/2013, 03:53:46 PM
 */
package pos;

import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ckaiser
 */
public class frmPagosDeuda extends javax.swing.JInternalFrame {
    MiModelo dtmData = new MiModelo();
    /** Creates new form frmPagosDeuda */
    public frmPagosDeuda(String va1, String va2, String valor, String saldo, String fecha_compra) {
        initComponents();
        
        Double totalDeuda = 0.00;
        
        dtmData.addColumn("N°");/*.setPreferredWidth(500)*/
        dtmData.addColumn("Fecha");
        dtmData.addColumn("Valor Pago");
        //1:3meses, 2:6 meses, 3: 9 meses, 4 :12 meses
        int plazo = Integer.parseInt(va1);
         //1:diario, 2:semanal, 3: quincenal, 4 :mensual
        int cuotas = Integer.parseInt(va2);
        int meses =0;
        if(plazo==1)
        {   
            meses = 3;
            txtPlazo.setText("3 MESES");
        }
        if(plazo==2)
        {
            meses = 6;
            txtPlazo.setText("6 MESES");
        }            
        if(plazo==3)
        {    
            meses = 9;
            txtPlazo.setText("9 MESES");
        }
        if(plazo==4)
        {    
            meses = 12;
            txtPlazo.setText("12 MESES");
        }
        int dias=0;
        if(cuotas==1)
        {   
            dias = 30;
            txtCuota.setText("DIARIO");
        }
        if(cuotas==2)
        {
            dias = 4;
            txtCuota.setText("SEMANAL");
        }
        if(cuotas==3)
        {
            dias =2;
            txtCuota.setText("QUINCENAL");
        }             
        if(cuotas==4)
        {
            dias = 1;
            txtCuota.setText("MENSUAL");
        }                
                    
        //int total = meses * dias;
        Double numeroPagos = Double.parseDouble(saldo) / Double.parseDouble(valor);
        DecimalFormat formateador = new DecimalFormat("####");
        Integer numeroPagosRedondeado = Integer.parseInt(formateador.format(numeroPagos)); 
        //establecer la fecha de hoy
        Date date1= new Date();
        Calendar fecha = Calendar.getInstance();
        fecha.setTime(date1); 
        
        
        //for(int i=0; i<total; i++)
        for(int i=0; i<numeroPagosRedondeado; i++)
        {           
            if(va2.equals("1"))       
            {
                //DIARIO
                fecha.add(Calendar.DAY_OF_MONTH, 1); 
            }
            else if(va2.equals("2"))  
            {
                //SEMANAL
                fecha.add(Calendar.DAY_OF_MONTH, 7);
            }
            else if(va2.equals("3"))  
            {
                //QUINCENAL
                fecha.add(Calendar.DAY_OF_MONTH, 15); 
            }
            else if(va2.equals("4"))  
            {
                //MENSUAL
                fecha.add(Calendar.MONTH, 1);
            }
            
            Date fecSegCarta = fecha.getTime();
            date1 = fecSegCarta;
            DateFormat df2 = new SimpleDateFormat("yyyy-MM-dd");
            String fecha2 = df2.format(fecSegCarta);
            
            Object[] nuevaFila = {i, fecha2, valor};
            dtmData.addRow(nuevaFila);
            totalDeuda = totalDeuda + Double.parseDouble(valor);
        }
        
        txtTotal.setText("" + totalDeuda);
        
        
        
    }
    
    public class MiModelo extends DefaultTableModel
    {
            @Override
       public boolean isCellEditable (int row, int column)
       {
            if ((column == 4)||(column == 5))
            {
                return true;
            }           
            return false;
       }
    } 

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPlazo = new javax.swing.JLabel();
        txtCuota = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setName("Form"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1.setModel(dtmData);
        jTable1.setName("jTable1"); // NOI18N
        jScrollPane1.setViewportView(jTable1);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(stinventario.STInventarioApp.class).getContext().getResourceMap(frmPagosDeuda.class);
        jPanel1.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setForeground(resourceMap.getColor("jLabel1.foreground")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel2.setForeground(resourceMap.getColor("jLabel1.foreground")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        txtPlazo.setForeground(resourceMap.getColor("txtPlazo.foreground")); // NOI18N
        txtPlazo.setText(resourceMap.getString("txtPlazo.text")); // NOI18N
        txtPlazo.setName("txtPlazo"); // NOI18N

        txtCuota.setForeground(resourceMap.getColor("txtCuota.foreground")); // NOI18N
        txtCuota.setText(resourceMap.getString("txtCuota.text")); // NOI18N
        txtCuota.setName("txtCuota"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPlazo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCuota, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPlazo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCuota))
                .addContainerGap())
        );

        txtTotal.setText(resourceMap.getString("txtTotal.text")); // NOI18N
        txtTotal.setName("txtTotal"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 802, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel txtCuota;
    private javax.swing.JLabel txtPlazo;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
